### ISSUE TITLE
Segfault with drone taser attack (latest github snap on Linux)

### ISSUE THREAD

**Issue by psavola** [hellrazor4223/hardmode-expansion#2]
The latest github snapshot of hardmode-expansion with OpenXcom 1.0.8d45159bf (2021-06-11 15:18) on Linux seems to always crash (segfault) if you do a drone taser attack. You hear an attack sound and the colors change on the screen, then the game freezes and hitting Esc causes the crash.

[03-04-2022_21-27-33]   [INFO]  Using software scaling routine. For best results, try an OpenGL filter.
[03-04-2022_21-30-50]   [INFO]  Playing flx, 320x200, 697 frames
[03-04-2022_21-30-55]   [INFO]  SDL_mixer initialized successfully.
[03-04-2022_21-47-35]   [FATAL] A fatal error has occurred: Segmentation fault. This usually indicates something missing in a mod.
[03-04-2022_21-47-35]   [FATAL] /tmp/.mount_OpenXca2zLpq/usr/bin/openxcom(OpenXcom::CrossPlatform::stackTrace(void*)+0x33) [0x6158a3]
[03-04-2022_21-47-35]   [FATAL] /tmp/.mount_OpenXca2zLpq/usr/bin/openxcom(OpenXcom::CrossPlatform::crashDump(void*, std::string const&)+0x427) [0x616457]
[03-04-2022_21-47-35]   [FATAL] /tmp/.mount_OpenXca2zLpq/usr/bin/openxcom(signalLogger(int)+0x2c) [0x4c577c]
[03-04-2022_21-47-35]   [FATAL] /lib64/libc.so.6(+0x4ead0) [0x7f4fa753ead0]
[03-04-2022_21-47-35]   [FATAL] /tmp/.mount_OpenXca2zLpq/usr/bin/openxcom(OpenXcom::Map::drawTerrain(OpenXcom::Surface*)+0x31e2) [0x5cc6a2]
[03-04-2022_21-47-35]   [FATAL] /tmp/.mount_OpenXca2zLpq/usr/bin/openxcom(OpenXcom::Map::draw()+0x2ab) [0x5cd27b]
[03-04-2022_21-47-35]   [FATAL] /tmp/.mount_OpenXca2zLpq/usr/bin/openxcom(OpenXcom::Surface::blit(OpenXcom::Surface*)+0x63) [0x6e26e3]
[03-04-2022_21-47-35]   [FATAL] /tmp/.mount_OpenXca2zLpq/usr/bin/openxcom(OpenXcom::State::blit()+0x4c) [0x6e0f9c]
[03-04-2022_21-47-35]   [FATAL] /tmp/.mount_OpenXca2zLpq/usr/bin/openxcom(OpenXcom::Game::run()+0x5f8) [0x630218]
[03-04-2022_21-47-35]   [FATAL] /tmp/.mount_OpenXca2zLpq/usr/bin/openxcom(main+0x12c) [0x4ad92c]
[03-04-2022_21-47-35]   [FATAL] /lib64/libc.so.6(__libc_start_main+0xf3) [0x7f4fa752aca3]
[03-04-2022_21-47-35]   [FATAL] /tmp/.mount_OpenXca2zLpq/usr/bin/openxcom(+0xaf8da) [0x4af8da]
[03-04-2022_21-47-58]   [FATAL] OpenXcom has crashed: Segmentation fault. This usually indicates something missing in a mod.
![Screenshot from 2022-04-03 21-47-41](https://user-images.githubusercontent.com/95160994/161443538-38f1a43a-7d71-491d-a641-305dd5e6c07a.png)

**Comment by psavola** [comment]
I updated to the latest OpenXcom github, compiled with debug and ran the game through gdb to get debug symbols. This is probably much more useful:

(gdb) bt full
#0  0x000000000078d056 in OpenXcom::Surface::getHeight (this=0x0) at /home/psavola/programs/code-openxcom/src/Basescape/../Engine/Surface.h:223
No locals.
#1  0x00000000008a3986 in OpenXcom::Map::drawTerrain (this=0x58e7b80, surface=0x58e7b80) at /home/psavola/programs/code-openxcom/src/Battlescape/Map.cpp:1227
        i = 0x609f010
        frameNumber = 0
        tmpSurface = 0x0
        tile = 0x0
        beginX = 0
        endX = 40
        beginY = 0
        endY = 40
        beginZ = 0
        endZ = 1
        mapPosition = {x = 40, y = 40, z = 1}
        screenPosition = {x = 480, y = 242, z = 1}
        bulletPositionScreen = {x = 493, y = 276, z = 0}
        bulletLowX = 16000
        bulletLowY = 16000
        bulletLowZ = 16000
        bulletHighX = 0
        bulletHighY = 0
        bulletHighZ = 0
        dummy = 38
        unit = 0x64f32e0
        tileShade = 16
        wallShade = 2
        tileColor = 0
        obstacleShade = 16
        arrowBob = {0, 1, 2, 1, 0, 1, 2, 1}
        _numWaypid = 0x0
        pathfinderTurnedOn = false
#2  0x000000000089de9c in OpenXcom::Map::draw (this=0x58e7b80) at /home/psavola/programs/code-openxcom/src/Battlescape/Map.cpp:223
        t = 0x62a7c10
#3  0x00000000009b6310 in OpenXcom::Surface::blit (this=0x58e7b80, surface=0x50dfe00) at /home/psavola/programs/code-openxcom/src/Engine/Surface.cpp:648
--Type <RET> for more, q to quit, c to continue without paging--c
        cropper = 0x50cc920
        target = {x = -9408, y = -1, w = 32767, h = 0}
#4  0x00000000009b3649 in OpenXcom::State::blit (this=0x5ee55f0) at /home/psavola/programs/code-openxcom/src/Engine/State.cpp:306
        i = 0x58e7b80
#5  0x000000000090812d in OpenXcom::Game::run (this=0x5039360) at /home/psavola/programs/code-openxcom/src/Engine/Game.cpp:324
        i = 0x5ee55f0
        runningState = OpenXcom::Game::RUNNING
        kbFocusRun = {OpenXcom::Game::RUNNING, OpenXcom::Game::RUNNING, OpenXcom::Game::SLOWED, OpenXcom::Game::PAUSED}
        stateRun = {OpenXcom::Game::SLOWED, OpenXcom::Game::PAUSED, OpenXcom::Game::PAUSED, OpenXcom::Game::PAUSED}
        startupEvent = false
#6  0x000000000078382f in main (argc=1, argv=0x7fffffffdf08) at /home/psavola/programs/code-openxcom/src/main.cpp:121
        title = <incomplete type>

**Comment by MeridianOXC** [comment]
It's caused by missing sprites.
I wrote more info into the forum post.

**Comment by hellrazor4223** [comment]
I fixed the issue see newest snapshot. :)
